services:
  postgres:
    image: postgres:15
    container_name: gacha_tracker_db
    environment:
      POSTGRES_DB: gacha_tracker
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data: